kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pan-prostate-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Ti
  storageClassName: slow
