apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-store-pvc
    namespace: default
  capacity:
    storage: 94Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /redis-store
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tracker
